#!/bin/bash
# Generate source ISO for all F${RELEASE} x86_64 spins
set -x
source /tmp/snapshot_id && \
pushd /usr/share && \
git clone https://pagure.io/forks/jsteffan/fedora-kickstarts.git && \
pushd /usr/share/fedora-kickstarts && \
git checkout fspin-f30 && \
\cp -f /tmp/fspin-snapshot-repo-not-rawhide-with-source.ks fedora-repo-not-rawhide.ks && \
sed -i '/%include fedora-repo.ks/d' fedora-live-base.ks && \
cp /tmp/all-spins.ks . && \
ksflatten --config all-spins.ks -o flat-all.ks --version F${RELEASE} && \
mkfs.ext4 -F /dev/nvme0n1 && \
mkdir -p /usr/share/fedora-kickstarts/${RELEASE} && \
mount /dev/nvme0n1 /usr/share/fedora-kickstarts/${RELEASE} && \
mkdir -p /usr/share/fedora-kickstarts/${RELEASE}/cache && \
mount -o bind /var/cache/pungi /usr/share/fedora-kickstarts/${RELEASE}/cache && \
pungi -G -c flat-all.ks --name ${SPIN_ID} --ver ${RELEASE} --force && \
pungi -C -c flat-all.ks --name ${SPIN_ID} --ver ${RELEASE} --force && \
pungi -I -c flat-all.ks --name ${SPIN_ID} --ver ${RELEASE} --sourceisos --force && \
popd && \
pushd /usr/share/fedora-kickstarts/${RELEASE}/source/iso && \
mv *.iso F${RELEASE}-source-${SPIN_ID}.iso && \
sha512sum *.iso > CHECKSUM512-${SPIN_ID}-DVD-source-${RELEASE} && \
popd
