#!/bin/bash
# Update mirror for target releases, creating a stable target for downstream jobs
set -x

MIRROR_HOST='ftp-chi.osuosl.org'
MIRROR_PATH='fedora/linux'
MIRROR_EXCLUDE='debug/*'
MIRROR_SNAPSHOTS=5
FEDORA_VERSION=37

# Create paths
mkdir -p /mirror/latest/releases/${FEDORA_VERSION}/Everything/x86_64/os/ \
         /mirror/latest/updates/${FEDORA_VERSION}/x86_64/ \

# Update local main copy of F${FEDORA_VERSION} x86_64 mirror
rsync -Pavy --delete-after --exclude ${MIRROR_EXCLUDE} ${MIRROR_HOST}::${MIRROR_PATH}/releases/${FEDORA_VERSION}/Everything/x86_64/os/ /mirror/latest/releases/${FEDORA_VERSION}/Everything/x86_64/os/ || exit 1
rsync -Pavy --delete-after --exclude ${MIRROR_EXCLUDE} dl.fedoraproject.org::fedora-linux-releases/${FEDORA_VERSION}/Everything/x86_64/os/ /mirror/latest/releases/${FEDORA_VERSION}/Everything/x86_64/os/ || exit 1

# Update local main copy of F${FEDORA_VERSION} updates x86_64 mirror
rsync -Pavy --delete-after --exclude ${MIRROR_EXCLUDE} ${MIRROR_HOST}::${MIRROR_PATH}/updates/${FEDORA_VERSION}/Everything/x86_64/ /mirror/latest/updates/${FEDORA_VERSION}/x86_64/ || exit 1
rsync -Pavy --delete-after --exclude ${MIRROR_EXCLUDE} dl.fedoraproject.org::fedora-linux-updates/${FEDORA_VERSION}/Everything/x86_64/ /mirror/latest/updates/${FEDORA_VERSION}/x86_64/ || exit 1

# Create a tagged repo for all downstream jobs
SNAPSHOT_ID=$(date --utc +%F-%s)
echo "Creating ${SNAPSHOT_ID}..."
mkdir -p /mirror/${SNAPSHOT_ID}/
cp -val /mirror/latest/* /mirror/${SNAPSHOT_ID}/
echo "${SNAPSHOT_ID}" > /mirror/latest_snapshot
echo "Cleaning out old snapshots..."
snapshots=(); while read -rd '' _ d; do snapshots+=("$d"); done < <(find /mirror -maxdepth 1 -name '*-*-*-*' -type d -printf '%T@ %p\0'|sort -zrn)
for old_snapshot in ${snapshots[@]:${MIRROR_SNAPSHOTS}}; do rm -rf ${old_snapshot}; done
echo "Snapshot ${SNAPSHOT_ID} is ready for use!"
echo "Current storage used:"
df -h /mirror | tee /mirror/storage_usage
