#!/bin/bash
# Update mirror for target releases, creating a stable target for downstream jobs
set -x

MIRROR_HOST='mirror.oss.ou.edu'
#MIRROR_HOST='mirror.cc.vt.edu'
MIRROR_EXCLUDE='debug/*'
MIRROR_SNAPSHOTS=5

# Create paths
mkdir -p /mirror/latest/releases/29/Everything/x86_64/os/ \
         /mirror/latest/releases/29/Everything/source/tree \
         /mirror/latest/updates/29/x86_64/ \
         /mirror/latest/updates/29/SRPMS/

# Update local main copy of F29 x86_64 mirror
rsync -Pavy --delete-after --exclude ${MIRROR_EXCLUDE} ${MIRROR_HOST}::fedora/linux/releases/29/Everything/x86_64/os/ /mirror/latest/releases/29/Everything/x86_64/os/
rsync -Pavy --delete-after --exclude ${MIRROR_EXCLUDE} dl.fedoraproject.org::fedora-linux-releases/29/Everything/x86_64/os/ /mirror/latest/releases/29/Everything/x86_64/os/

# Update local main copy of F29 source mirror
rsync -Pavy --delete-after --exclude ${MIRROR_EXCLUDE} ${MIRROR_HOST}::fedora/linux/releases/29/Everything/source/tree/ /mirror/latest/releases/29/Everything/source/tree/
rsync -Pavy --delete-after --exclude ${MIRROR_EXCLUDE} dl.fedoraproject.org::fedora-linux-releases/29/Everything/source/tree/ /mirror/latest/releases/29/Everything/source/tree/

# Update local main copy of F29 updates x86_64 mirror
rsync -Pavy --delete-after --exclude ${MIRROR_EXCLUDE} ${MIRROR_HOST}::fedora/linux/updates/29/Everything/x86_64/ /mirror/latest/updates/29/x86_64/
rsync -Pavy --delete-after --exclude ${MIRROR_EXCLUDE} dl.fedoraproject.org::fedora-linux-updates/29/Everything/x86_64/ /mirror/latest/updates/29/x86_64/

# Update local main copy of F29 updates source mirror
rsync -Pavy --delete-after --exclude ${MIRROR_EXCLUDE} ${MIRROR_HOST}::fedora/linux/updates/29/Everything/SRPMS/ /mirror/latest/updates/29/SRPMS/
rsync -Pavy --delete-after --exclude ${MIRROR_EXCLUDE} dl.fedoraproject.org::fedora-linux-updates/29/Everything/SRPMS/ /mirror/latest/updates/29/SRPMS/

# Create a tagged repo for all downstream jobs
SNAPSHOT_ID=$(date --utc +%F-%s)
echo "Creating ${SNAPSHOT_ID}..."
mkdir -p /mirror/${SNAPSHOT_ID}/
cp -val /mirror/latest/* /mirror/${SNAPSHOT_ID}/
echo "${SNAPSHOT_ID}" > /mirror/latest_snapshot
echo "Cleaning out old snapshots..."
snapshots=(); while read -rd '' _ d; do snapshots+=("$d"); done < <(find /mirror -maxdepth 1 -name '*-*-*-*' -type d -printf '%T@ %p\0'|sort -zrn)
for old_snapshot in ${snapshots[@]:${MIRROR_SNAPSHOTS}}; do rm -rf ${old_snapshot}; done
echo "Snapshot ${SNAPSHOT_ID} is ready for use!"
echo "Current storage used:"
df -h /mirror | tee /mirror/storage_usage
