apiVersion: batch/v1
kind: Job
metadata:
  name: fspin-repo-update
spec:
  template:
    spec:
      containers:
      - name: fspin-repo-update
        image: gcr.io/fspin36-23276e975a/fspin-repo-update
        volumeMounts:
        - mountPath: /mirror
          name: fspin-mirror-storage
      volumes:
      - name: fspin-mirror-storage
        gcePersistentDisk:
          pdName: fspin-mirror-storage
          fsType: ext4
      restartPolicy: OnFailure
