apiVersion: batch/v1
kind: Job
metadata:
  name: fspin-publish
spec:
  template:
    spec:
      containers:
      - name: fspin-publish
        image: gcr.io/fspin-40572d9516/fspin-publish
      restartPolicy: Never
  backoffLimit: 1
