apiVersion: batch/v1
kind: Job
metadata:
  name: fspin-cloud-image-import
spec:
  template:
    spec:
      containers:
      - name: fspin-cloud-image-import
        image: gcr.io/fspin-199819/fspin-cloud-image-import
      restartPolicy: OnFailure
