apiVersion: batch/v1
kind: Job
metadata:
  name: fspin-x86-64-builder-update
spec:
  template:
    spec:
      containers:
      - name: fspin-x86-64-builder-update
        image: gcr.io/fspin-ba0660e7cf/fspin-x86-64-builder-update
      restartPolicy: OnFailure
