apiVersion: batch/v1
kind: Job
metadata:
  name: fspin-${RELEASE}-lmc-${TARGET}
  labels:
    jobgroup: lmc-spinner
spec:
  template:
    metadata:
      name: fspin-${RELEASE}-x86-64-livemedia-creator
      labels:
        jobgroup: lmc-spinner
    spec:
      containers:
      - name: fspin-${RELEASE}-x86-64-livemedia-creator
        image: gcr.io/fspin-199819/fspin-x86-64-livemedia-creator
        env:
          - name: TARGET
            value: "${TARGET}"
          - name: RELEASE
            value: "${RELEASE}"
        volumeMounts:
        - name: prevent-scale-down
          mountPath: /opt/prevent-scale-down
        resources:
          requests:
            cpu: "100m"
      volumes:
      - name: prevent-scale-down
        emptyDir: {}
      restartPolicy: OnFailure
