apiVersion: batch/v1
kind: Job
metadata:
  name: fspin-publish
spec:
  template:
    spec:
      containers:
      - name: fspin-publish
        image: gcr.io/fspin-199819/fspin-publish
      restartPolicy: Never
