apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: repo-fspin-org-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: repo-fspin-org-deployment
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50
