apiVersion: apps/v1
kind: Service
apiVersion: v1
metadata:
  name: repo-fspin-org
  annotations:
    external-dns.alpha.kubernetes.io/hostname: repo.k8s.fspin.org.
    external-dns.alpha.kubernetes.io/ttl: "60"
spec:
  selector:
    app: repo
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
