#!/bin/bash
# Compose from upstream Fedora 27 x86_64 ${SPIN_NAME}
set -x
source /tmp/snapshot_id && \
export SPIN_SHORT_NAME=`echo $SPIN_NAME|cut -c1-4|awk '{print toupper($0)}'` && \
pushd /usr/share/spin-kickstarts  && \
\cp -f /tmp/fspin-snapshot-repo-not-rawhide-with-source.ks fedora-repo-not-rawhide.ks && \
mv fedora-live-mate_compiz.ks fedora-live-mate-compiz.ks && \
ksflatten --config fedora-live-${SPIN_NAME}.ks -o flat-fedora-live-${SPIN_NAME}.ks --version F27 && \
mock -r fspin-snapshot-27-x86_64 --init && \
mock -r fspin-snapshot-27-x86_64 --install lorax-lmc-novirt && \
mock -r fspin-snapshot-27-x86_64 --copyin flat-fedora-live-${SPIN_NAME}.ks . && \
mock -r fspin-snapshot-27-x86_64 --old-chroot --chroot "livemedia-creator --ks flat-fedora-live-${SPIN_NAME}.ks --no-virt --resultdir /var/lmc --project F27-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live --make-iso --volid F27-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live --iso-only --iso-name F27-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live.iso --releasever 27 --title F27-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live --macboot" && \
popd && \
pushd /var/lib/mock/fspin-snapshot-27-x86_64/root/var/lmc/ && \
sha512sum * > CHECKSUM512-F27-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live && \
transmission-create -p -s 2048 \
	-c "ISO SHA512SUM: $(cat CHECKSUM512*)" \
	-t http://respins.fedorainfracloud.org:6969/announce \
	-o F27-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live.torrent \
	F27-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live.iso && \
popd
