#!/bin/bash
# Run spin snippets in the latest GCE fspin image for ${RELEASE} x86_64
set -x
LATEST_IMAGE=$(gcloud compute images list --filter="name~fspin-${RELEASE}-x86-64" --sort-by="~creationTimestamp" --limit=1 --format="json(NAME)"|jq -r .[].name)
INSTANCE_NAME="${LATEST_IMAGE}-lmc-$(cat /proc/sys/kernel/random/uuid|awk -F- '{print $5}')-${TARGET}"
RESULTS_LOCATION="gs://build-results.fspin.org/live/${INSTANCE_NAME}/"
ZONE="us-west2-a"
BUILD_SCRIPT="fspin-x86-64-${TARGET}"

# Create instance to run lmc
echo "Starting spin for ${TARGET} on ${INSTANCE_NAME} using base image ${LATEST_IMAGE}..." && \
gcloud compute instances create ${INSTANCE_NAME} --zone ${ZONE} --image ${LATEST_IMAGE} --boot-disk-size 30GB --boot-disk-type pd-ssd --local-ssd interface=NVME --machine-type n1-highcpu-16 --preemptible --scopes storage-rw && \

# Prep instance with target script
gcloud compute scp /opt/spins/${BUILD_SCRIPT} ${INSTANCE_NAME}:/tmp/build_script --zone ${ZONE} && \

# Run selected snippet
gcloud compute ssh ${INSTANCE_NAME} --zone ${ZONE} --command "sudo bash -c 'export RELEASE=${RELEASE}; /tmp/build_script'" && \

# Copy out results
gcloud compute ssh ${INSTANCE_NAME} --zone ${ZONE} --command "gsutil cp /var/lib/mock/*/root/var/lmc/* ${RESULTS_LOCATION}" && \
echo "SUCCESS: Results located at ${RESULTS_LOCATION}"
result=$?

# Cleanup
echo "Deleting ${INSTANCE_NAME}..."
gcloud -q compute instances delete ${INSTANCE_NAME} --zone ${ZONE} --delete-disks all
exit $result
