#!/bin/bash
# Compose from upstream Fedora ${RELEASE} x86_64 ${SPIN_NAME}
set -x
source /tmp/snapshot_id && \
export SPIN_SHORT_NAME=`echo $SPIN_NAME|cut -c1-4|awk '{print toupper($0)}'` && \
pushd /usr/share && \
git clone https://pagure.io/fedora-kickstarts.git && \
pushd /usr/share/fedora-kickstarts && \
git checkout f${RELEASE} && \
\cp -f /tmp/fspin-snapshot-repo-not-rawhide-with-source.ks fedora-repo-not-rawhide.ks && \
mv fedora-live-mate_compiz.ks fedora-live-mate-compiz.ks && \
ksflatten --config fedora-live-${SPIN_NAME}.ks -o flat-fedora-live-${SPIN_NAME}.ks --version F${RELEASE} && \
mkfs.ext4 -F /dev/nvme0n1 && \
mount /dev/nvme0n1 /var/lib/mock && \
mock -v -r fspin-snapshot-x86_64 --init && \
mock -v -r fspin-snapshot-x86_64 --install lorax\* && \
mock -v -r fspin-snapshot-x86_64 --copyin flat-fedora-live-${SPIN_NAME}.ks . && \
mock -v -r fspin-snapshot-x86_64 --old-chroot --chroot "livemedia-creator --ks flat-fedora-live-${SPIN_NAME}.ks --no-virt --resultdir /var/lmc --project F${RELEASE}-${SPIN_SHORT_NAME}-x86_64-LIVE-${SPIN_ID} --make-iso --volid F${RELEASE}-${SPIN_SHORT_NAME}-x86_64-LIVE-${SPIN_ID} --iso-only --iso-name F${RELEASE}-${SPIN_SHORT_NAME}-x86_64-LIVE-${SPIN_ID}.iso --releasever ${RELEASE} --macboot" && \
popd && popd && \
pushd /var/lib/mock/fspin-snapshot-x86_64/root/var/lmc/ && \
sha512sum * > CHECKSUM512-F${RELEASE}-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live && \
transmission-create -p -s 2048 \
	-c "ISO SHA512SUM: $(cat CHECKSUM512*)" \
	-t http://respins.fedorainfracloud.org:6969/announce \
	-o F${RELEASE}-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live.torrent \
	F${RELEASE}-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live.iso && \
	echo "`transmission-show F${RELEASE}-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live.torrent | \
	awk '/Hash/{print $2}'` F${RELEASE}-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live.iso" > \
	F${RELEASE}-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-torrenthash && \
popd
