#!/bin/bash
# Run spin snippets in the latest GCE fspin image for ${RELEASE} x86_64
set -x
LATEST_IMAGE=$(gcloud compute images list --filter="name~fspin-${RELEASE}-x86-64" --sort-by="~creationTimestamp" --limit=1 --format="json(NAME)"|jq -r .[].name)
PROJECT_NAME="fspin36-1d2e88cf18"
INSTANCE_NAME="${LATEST_IMAGE}-lmc-$(cat /proc/sys/kernel/random/uuid|awk -F- '{print $1}')-${TARGET}"
RESULTS_LOCATION="gs://${PROJECT_NAME}-build-results.fspin.org/live/${INSTANCE_NAME}/"
ZONE="us-central1-a"
BUILD_SCRIPT="fspin-x86-64-${TARGET}"
TRIES="0"
LIMIT="10"
SLEEP="30"

# Create instance to run lmc
echo "Starting spin for ${TARGET} on ${INSTANCE_NAME} using base image ${LATEST_IMAGE}..." && \
gcloud compute instances create ${INSTANCE_NAME} --preemptible --zone ${ZONE} --image ${LATEST_IMAGE} --boot-disk-size 30GB --boot-disk-type pd-ssd --local-ssd interface=NVME --machine-type n1-standard-8 --scopes storage-rw && \

# Ensure instance is available and connections are working
while [[ $TRIES -lt $LIMIT ]]; do
       gcloud compute ssh ${INSTANCE_NAME} --zone ${ZONE} --command 'uptime' && break || \
       sleep $SLEEP && \
       let TRIES=TRIES+1
done

# Prep instance with target script
gcloud compute scp /opt/spins/${BUILD_SCRIPT} ${INSTANCE_NAME}:/tmp/build_script --zone ${ZONE} && \

# Run selected snippet
gcloud compute ssh ${INSTANCE_NAME} --zone ${ZONE} --command "sudo bash -c 'export RELEASE=${RELEASE}; /tmp/build_script'" && \

# Copy out results
gcloud compute ssh ${INSTANCE_NAME} --zone ${ZONE} --command "gsutil -m cp -c /var/lib/mock/*/root/var/lmc/* ${RESULTS_LOCATION}" && \
echo "SUCCESS: Results located at ${RESULTS_LOCATION}"
result=$?

# Cleanup
echo "Deleting ${INSTANCE_NAME}..."
gcloud -q compute instances delete ${INSTANCE_NAME} --zone ${ZONE} --delete-disks all
exit $result
