apiVersion: batch/v1
kind: Job
metadata:
  name: fspin-f28-workstation
  labels:
    jobgroup: lmc-spinner
spec:
  template:
    metadata:
      name: fspin-f28-workstation
      labels:
        jobgroup: lmc-spinner
    spec:
      containers:
      - name: build-f28-workstation
        image: gcr.io/fspin-199819/fspin-x86-64-livemedia-creator
        env:
          - name: TARGET
            value: "workstation"
          - name: RELEASE
            value: "28"
        volumeMounts:
        - name: prevent-scale-down
          mountPath: /opt/prevent-scale-down
        resources:
          requests:
            cpu: "100m"
      volumes:
      - name: prevent-scale-down
        emptyDir: {}
      restartPolicy: OnFailure
      backoffLimit: 60
