apiVersion: batch/v1
kind: Job
metadata:
  name: fspin-f29-source
  labels:
    jobgroup: source-spinner
spec:
  backoffLimit: 10
  template:
    metadata:
      name: fspin-f29-source
      labels:
        jobgroup: source-spinner
    spec:
      containers:
      - name: fspin-f29-x86-64-source
        image: gcr.io/fspin-199819/fspin-x86-64-pungi
        env:
          - name: RELEASE
            value: "29"
        volumeMounts:
        - name: prevent-scale-down
          mountPath: /opt/prevent-scale-down
        resources:
          requests:
            cpu: "100m"
      volumes:
      - name: prevent-scale-down
        emptyDir: {}
      restartPolicy: OnFailure
