apiVersion: batch/v1
kind: Job
metadata:
  name: fspin-f35-soas
  labels:
    jobgroup: lmc-spinner
spec:
  backoffLimit: 20
  template:
    metadata:
      name: fspin-f35-soas
      labels:
        jobgroup: lmc-spinner
    spec:
      containers:
      - name: build-f35-soas
        image: gcr.io/fspin36-5e643e3932/fspin-x86-64-livemedia-creator
        env:
          - name: TARGET
            value: "soas"
          - name: RELEASE
            value: "35"
        volumeMounts:
        - name: prevent-scale-down
          mountPath: /opt/prevent-scale-down
        resources:
          requests:
            cpu: "100m"
      volumes:
      - name: prevent-scale-down
        emptyDir: {}
      restartPolicy: OnFailure
