apiVersion: batch/v1
kind: Job
metadata:
  name: fspin-28-pungi
  labels:
    jobgroup: pungi-spinner
spec:
  template:
    metadata:
      name: fspin-28-x86-64-pungi
      labels:
        jobgroup: pungi-spinner
    spec:
      containers:
      - name: fspin-28-x86-64-pungi
        image: gcr.io/fspin-199819/fspin-x86-64-pungi
        env:
          - name: RELEASE
            value: "28"
        volumeMounts:
        - name: prevent-scale-down
          mountPath: /opt/prevent-scale-down
        resources:
          requests:
            cpu: "100m"
      volumes:
      - name: prevent-scale-down
        emptyDir: {}
      restartPolicy: OnFailure
