apiVersion: batch/v1
kind: Job
metadata:
  name: fspin-f32-kde
  labels:
    jobgroup: lmc-spinner
spec:
  backoffLimit: 20
  template:
    metadata:
      name: fspin-f32-kde
      labels:
        jobgroup: lmc-spinner
    spec:
      containers:
      - name: build-f32-kde
        image: gcr.io/fspin-265404/fspin-x86-64-livemedia-creator
        env:
          - name: TARGET
            value: "kde"
          - name: RELEASE
            value: "32"
        volumeMounts:
        - name: prevent-scale-down
          mountPath: /opt/prevent-scale-down
        resources:
          requests:
            cpu: "100m"
      volumes:
      - name: prevent-scale-down
        emptyDir: {}
      restartPolicy: OnFailure
