apiVersion: batch/v1
kind: Job
metadata:
  name: fspin-f34-i3
  labels:
    jobgroup: lmc-spinner
spec:
  backoffLimit: 20
  template:
    metadata:
      name: fspin-f34-i3
      labels:
        jobgroup: lmc-spinner
    spec:
      containers:
      - name: build-f34-i3
        image: gcr.io/fspin-7ce15ff175/fspin-x86-64-livemedia-creator
        env:
          - name: TARGET
            value: "i3"
          - name: RELEASE
            value: "34"
        volumeMounts:
        - name: prevent-scale-down
          mountPath: /opt/prevent-scale-down
        resources:
          requests:
            cpu: "100m"
      volumes:
      - name: prevent-scale-down
        emptyDir: {}
      restartPolicy: OnFailure
