#!/bin/bash
# Import upstream cloud base images into GCE for custom image family
set -x
IMPORT_TIME=$(date --utc +%s)
ZONE='us-west2-a'
PROJECT='fspin-199819'
#COMPAT_JSON_C_F28='https://jsteffan.fedorapeople.org/compat-json-c/f28/compat-json-c-0.12.1-5.fc28.x86_64.rpm'
#COMPAT_JSON_C_F29='https://jsteffan.fedorapeople.org/compat-json-c/f29/compat-json-c-0.12.1-5.fc29.x86_64.rpm'
#GCSDK_FAKE_BOOST_REGEX_F29='https://jsteffan.fedorapeople.org/gcsdk-fake-boost-regex/gcsdk-fake-boost-regex-1.53.0-1.fc29.x86_64.rpm'

gcloud config set project ${PROJECT}
gcloud config set compute/zone ${ZONE}

# We need F27 to inject json-c into the F28 image
#echo "Importing F27..." && \
#wget https://dl.fedoraproject.org/pub/fedora/linux/releases/27/CloudImages/x86_64/images/Fedora-Cloud-Base-27-1.6.x86_64.raw.xz && \
#unxz Fedora-Cloud-Base-27-1.6.x86_64.raw.xz && \
#gcloud --quiet beta compute images import fspin-27-1-6-x86-64-${IMPORT_TIME} \
#    --source-file Fedora-Cloud-Base-27-1.6.x86_64.raw \
#    --os centos-7 && \
#gcloud compute images create fspin-27-${IMPORT_TIME} \
#    --source-image fspin-27-1-6-x86-64-${IMPORT_TIME} \
#    --source-image-project ${PROJECT} \
#    --family fspin-27 && \

# WARNING: This requires that the --image-family fspin-27 already exists
# Not working with kernel < 4.16.6
# Needs earlier json-c injected into image for google components during the import process
#echo "Importing F28..." && \
# launch latest f27 image, download f28 image, decompress, mount, inject compat-json-c, unmount, pull raw image result
#gcloud compute instances create f28-inject-json-c \
#    --image-family fspin-27 \
#    --boot-disk-size 50GB \
#    --boot-disk-type pd-ssd \
#    --machine-type n1-standard-4 && \
#gcloud compute ssh f28-inject-json-c \
#    --command "sudo bash -c 'dnf -y install wget xz && wget https://kojipkgs.fedoraproject.org/packages/Fedora-Cloud-Base/28/20180507.0/images/Fedora-Cloud-Base-28-20180507.0.x86_64.raw.xz && unxz Fedora-Cloud-Base-28-20180507.0.x86_64.raw.xz'" && \
#gcloud compute ssh f28-inject-json-c \
#    --command "sudo bash -c 'dnf -y install libguestfs-tools && mkdir -p /fcb && LIBGUESTFS_BACKEND=direct guestmount -a Fedora-Cloud-Base-28-20180507.0.x86_64.raw -i /fcb'" && \
#gcloud compute ssh f28-inject-json-c \
#    --command "sudo bash -c 'rpm -Uvh --root /fcb ${COMPAT_JSON_C_F28}'" && \
#gcloud compute ssh f28-inject-json-c \
#    --command "sudo bash -c 'guestunmount /fcb && sleep 60'" && \
#gcloud compute scp f28-inject-json-c:Fedora-Cloud-Base-28-20180507.0.x86_64.raw . && \
#gcloud -q compute instances delete f28-inject-json-c --delete-disks all && \
#
## run f28 import with injected raw disk
#gcloud --quiet beta compute images import fspin-28-1-1-20180507-x86-64-${IMPORT_TIME} \
#    --source-file Fedora-Cloud-Base-28-20180507.0.x86_64.raw \
#    --os centos-7 && \
#gcloud compute images create fspin-28-${IMPORT_TIME} \
#    --source-image fspin-28-1-1-20180507-x86-64-${IMPORT_TIME} \
#    --source-image-project ${PROJECT} \
#    --family fspin-28

# WARNING: This requires that the --image-family fspin-28 already exists
# Needs earlier json-c and faked boost-regex injected into image for google components during the import process
#echo "Importing F29..." && \
# launch latest f28 image, download f29 image, decompress, mount, inject compat-json-c, unmount, pull raw image result
#gcloud compute instances create f29-inject-deps \
#    --image-family fspin-28 \
#    --boot-disk-size 50GB \
#    --boot-disk-type pd-ssd \
#    --machine-type n1-standard-4 && \
#gcloud compute ssh f29-inject-deps \
#    --command "sudo bash -c 'dnf -y install wget xz && wget https://dl.fedoraproject.org/pub/fedora/linux/releases/29/Cloud/x86_64/images/Fedora-Cloud-Base-29-1.2.x86_64.raw.xz && unxz Fedora-Cloud-Base-29-1.2.x86_64.raw.xz'" && \
#gcloud compute ssh f29-inject-deps \
#    --command "sudo bash -c 'dnf -y install libguestfs-tools && dnf -y update && mkdir -p /fcb && LIBGUESTFS_BACKEND=direct guestmount -a Fedora-Cloud-Base-29-1.2.x86_64.raw -i /fcb && echo \"nameserver 8.8.8.8\" > /fcb/etc/resolv.conf'" && \
#gcloud compute ssh f29-inject-deps \
#    --command "sudo bash -c 'chroot /fcb dnf -y install --releasever 29 ${COMPAT_JSON_C_F29} ${GCSDK_FAKE_BOOST_REGEX_F29}'" && \
#gcloud compute ssh f29-inject-deps \
#    --command "sudo bash -c 'chroot /fcb dnf clean all && rm -fv /fcb/etc/resolv.conf && guestunmount /fcb && sleep 60'" && \
#gcloud compute scp f29-inject-deps:Fedora-Cloud-Base-29-1.2.x86_64.raw . && \
#gcloud -q compute instances delete f29-inject-deps --delete-disks all && \
#
## run f29 import with injected raw disk
#gcloud --quiet beta compute images import fspin-29-1-2-x86-64-${IMPORT_TIME} \
#    --source-file Fedora-Cloud-Base-29-1.2.x86_64.raw \
#    --os centos-7 && \
#gcloud compute images create fspin-29-${IMPORT_TIME} \
#    --source-image fspin-29-1-2-x86-64-${IMPORT_TIME} \
#    --source-image-project ${PROJECT} \
#    --family fspin-29

#echo "Importing F30..." && \
## download upstream raw image
#wget https://download.fedoraproject.org/pub/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-30-1.2.x86_64.raw.xz && \
#unxz Fedora-Cloud-Base-30-1.2.x86_64.raw.xz && \
#
## run f30 import from upstream raw disk
#gcloud --quiet beta compute images import fspin-30-1-2-x86-64-${IMPORT_TIME} \
#    --source-file Fedora-Cloud-Base-30-1.2.x86_64.raw \
#    --os centos-7 && \
#gcloud compute images create fspin-30-${IMPORT_TIME} \
#    --source-image fspin-30-1-2-x86-64-${IMPORT_TIME} \
#    --source-image-project ${PROJECT} \
#    --family fspin-30

# Needs to import the gcp k8s & sdk gpg keys for the import to work
echo "Importing F31..." && \
# launch latest centos-8 image, download f31 image, decompress, mount, import needed gpg keys correctly, unmount, pull raw image result
gcloud compute instances create f31-workaround-gpg \
    --image-family centos-8 \
    --image-project centos-cloud \
    --boot-disk-size 50GB \
    --boot-disk-type pd-ssd \
    --machine-type n1-standard-4 && \
sleep 60 && \
gcloud compute ssh f31-workaround-gpg \
    --command "sudo bash -c 'dnf -y install wget xz && wget https://download.fedoraproject.org/pub/fedora/linux/releases/31/Cloud/x86_64/images/Fedora-Cloud-Base-31-1.9.x86_64.raw.xz && unxz Fedora-Cloud-Base-31-1.9.x86_64.raw.xz'" && \
gcloud compute ssh f31-workaround-gpg \
    --command "sudo bash -c 'dnf -y install libguestfs-tools && mkdir -p /fcb && LIBGUESTFS_BACKEND=direct guestmount -a Fedora-Cloud-Base-31-1.9.x86_64.raw -i /fcb && echo \"nameserver 8.8.8.8\" > /fcb/etc/resolv.conf'" && \
gcloud compute ssh f31-workaround-gpg \
    --command "sudo bash -c 'chroot /fcb curl https://raw.githubusercontent.com/fspin-k8s/fspin-infrastructure/master/repos/fspin-gcp-k8s-el7-x86_64.repo -o /etc/yum.repos.d/fspin-gcp-k8s-el7-x86_64.repo'" && \
gcloud compute ssh f31-workaround-gpg \
    --command "sudo bash -c 'chroot /fcb curl https://raw.githubusercontent.com/fspin-k8s/fspin-infrastructure/master/repos/fspin-gcp-sdk-el7-x86_64.repo -o /etc/yum.repos.d/fspin-gcp-sdk-el7-x86_64.repo'" && \
gcloud compute ssh f31-workaround-gpg \
    --command "sudo bash -c 'chroot /fcb dnf -y makecache'" && \ # FIXME: sudo su -; chroot /fcb; dnf -y makecache
gcloud compute ssh f31-workaround-gpg \
    --command "sudo bash -c 'rm -vf /fcb/etc/resolv.conf && sed -i s/\"enabled=1\"/\"enabled=0\"/g /fcb/etc/yum.repos.d/gcp-k8s-el7-x86_64.repo /fcb/etc/yum.repos.d/gcp-sdk-el7-x86_64.repo'" && \
gcloud compute ssh f31-workaround-gpg \
    --command "sudo bash -c 'guestunmount /fcb && sleep 60'" && \
gcloud compute scp f31-workaround-gpg:Fedora-Cloud-Base-31-1.9.x86_64.raw . && \
gcloud -q compute instances delete f31-workaround-gpg --delete-disks all && \

# XXX Start here

# run f31 import from upstream gpg imported raw disk
gcloud --quiet beta compute images import fspin-31-1-9-x86-64-${IMPORT_TIME} \
    --source-file Fedora-Cloud-Base-31-1.9.x86_64.raw \
    --os centos-7 && \
gcloud compute images create fspin-31-${IMPORT_TIME} \
    --source-image fspin-31-1-9-x86-64-${IMPORT_TIME} \
    --source-image-project ${PROJECT} \
    --family fspin-31
