#!/bin/bash
# Compose from upstream Fedora 27 x86_64 ${SPIN_NAME}
source /tmp/snapshot_id
export SPIN_ID=`echo $SNAPSHOT_ID|awk -F- '{print $4}'`
pushd /usr/share/spin-kickstarts
cp /tmp/fspin-snapshot-repo-not-rawhide-with-source.ks fedora-repo-not-rawhide.ks
mv fedora-live-mate_compiz.ks fedora-live-mate-compiz.ks
ksflatten --config fedora-live-${SPIN_NAME}.ks -o flat-fedora-live-${SPIN_NAME}.ks --version F27
livemedia-creator --ks flat-fedora-live-${SPIN_NAME}.ks --no-virt --resultdir /var/lmc --project Fedora-27-${SPIN_NAME}-${SPIN_ID}-Live --make-iso --volid Fedora-27-${SPIN_NAME}-${SPIN_ID} --iso-only --iso-name Fedora-27-${SPIN_NAME}-${SPIN_ID}-x86-64.iso --releasever 27 --title Fedora-27-${SPIN_NAME}-${SPIN_ID}-live --macboot
popd
