#!/bin/bash
# Create a release candidate and push to GCS for the mirrors
set -x
source /opt/release_id
RELEASE_STRING=`echo ${RELEASE_ID}|sed 's/-//g'`
RESULTS_LOCATION="gs://build-results.fspin.org/releases/"
pushd ${RELEASE_ID}
echo "Downloading spins for ${RELEASE_ID}..." && \
gsutil cp gs://build-results.fspin.org/*/*/*${RELEASE_STRING}* . && \
echo "Generating checksums for ${RELEASE_ID}..." && \
sha512sum * > CHECKSUM512-${RELEASE_STRING}
for SPIN in $(ls *.iso); do
  echo "Creating torrent for ${SPIN}..." && \
  mktorrent-borg -p -l 128 \
  -a http://respins.fedorainfracloud.org:6969/announce \
  -c "ISO SHA512SUM: `grep ${SPIN} CHECKSUM512-${RELEASE_STRING}`" \
  $SPIN
done
popd
echo "Publishing ${RELEASE_ID} to ${RESULTS_LOCATION}..." && \
gsutil cp ${RELEASE_ID} ${RESULTS_LOCATION} && \
echo "SUCCESS: Results located at ${RESULTS_LOCATION}"

