Master:
  ServiceType: ClusterIP
  ingress:
    enabled: true
    hostName: "jenkins.fspin.org"
    annotations:
      kubernetes.io/ingress.class: traefik
  InstallPlugins:
    - kubernetes:1.14.3
    - workflow-aggregator:2.6
    - workflow-job:2.31
    - credentials-binding:1.17
    - git:3.9.3
    - openid:2.3
    - matrix-auth:2.3

Agent:
  Image: gcr.io/fspin-199819/fspin-jenkins-runner
  ImageTag: "latest"
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1024Mi"

rbac:
  install: true
  serviceAccountName: fspin-jenkins
  apiVersion: v1beta1
  roleRef: cluster-admin
