master:
  serviceType: ClusterIP
  ingress:
    enabled: true
    hostName: "jenkins.fspin.org"
    annotations:
      kubernetes.io/ingress.class: traefik
  installPlugins:
    - kubernetes:1.15.0
    - workflow-aggregator:2.6
    - workflow-job:2.32
    - credentials-binding:1.18
    - git:3.9.3
    - openid:2.3
    - matrix-auth:2.3

agent:
  image: gcr.io/fspin-199819/fspin-jenkins-runner
  imageTag: "latest"
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1024Mi"

serviceAccount:
  name: fspin-jenkins
