master:
  serviceType: ClusterIP
  ingress:
    enabled: true
    hostName: "jenkins.fspin.org"
    annotations:
      kubernetes.io/ingress.class: traefik
  installPlugins:
    - kubernetes:1.17.1
    - workflow-aggregator:2.6
    - workflow-job:2.33
    - credentials-binding:1.19
    - git:3.10.1
    - openid:2.3
    - matrix-auth:2.4.2

agent:
  image: gcr.io/fspin-199819/fspin-jenkins-runner
  tag: "latest"
  podName: fspin-jenkins-run
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

serviceAccountAgent:
  name: fspin-jenkins-agent
  create: false
