controller:
  serviceType: ClusterIP
  ingress:
    enabled: true
    hostName: "jenkins.fspin.org"
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/acme-challenge-type: http01
    tls:
      - secretName: jenkins-fspin-org-tls
        hosts:
          - jenkins.fspin.org

  tag: "lts"
  installLatestPlugins: true
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - workflow-job
    - credentials-binding
    - git
    - openid
    - matrix-auth

agent:
  image: gcr.io/fspin-265404/fspin-jenkins-runner
  tag: "latest"
  podName: fspin-jenkins-run
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

serviceAccountAgent:
  name: fspin-jenkins-agent
  create: false
