Master:
  ServiceAnnotations:
    external-dns.alpha.kubernetes.io/hostname: jenkins.k8s.fspin.org.
    external-dns.alpha.kubernetes.io/ttl: "60"
  InstallPlugins:
    - kubernetes:1.1
    - workflow-aggregator:2.5
    - workflow-job:2.15
    - credentials-binding:1.13
    - git:3.6.4

Agent:
  Image: gcr.io/fspin-199819/fspin-jenkins-runner

rbac:
  install: true
  serviceAccountName: fspin-jenkins
  apiVersion: v1beta1
  roleRef: cluster-admin
