controller:
  JCasC:
    securityRealm: |-
      openIdSso:
        endpoint: "https://id.fedoraproject.org"
    authorizationStrategy: |-
      globalMatrix:
        permissions:
        - "GROUP:Overall/Administer:respins-sig"
    configScripts:
      seed-jobs: |
        security:
          globalJobDslSecurityConfiguration:
            useScriptSecurity: false
        jobs:
          - url: https://raw.githubusercontent.com/fspin-k8s/fspin-infrastructure/main/jenkins-jobs/seed_pipelines.groovy
  disableRememberMe: true
  serviceType: ClusterIP
  ingress:
    enabled: true
    hostName: "jenkins.fspin.org"
    ingressClassName: nginx
    annotations:
      kubernetes.io/tls-acme: "true"
      certmanager.k8s.io/acme-challenge-type: http01
    tls:
      - secretName: jenkins-fspin-org-tls
        hosts:
          - jenkins.fspin.org
  installLatestPlugins: true
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - workflow-job
    - credentials-binding
    - git
    - openid
    - matrix-auth
    - matrix-project
    - configuration-as-code
    - job-dsl
    - pipeline-stage-view
    - pipeline-graph-view

agent:
  image:
    repository: gcr.io/fspin-40572d9516/fspin-jenkins-runner
    tag: "latest"
  podName: fspin-jenkins-run
  customJenkinsLabels: fspin-jenkins-run
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

additionalAgents:
  fspin-jenkins-repo:
    podName: fspin-jenkins-repo
    customJenkinsLabels: fspin-jenkins-repo
    # Not working, need to manually set in the container template
    # advanced settings for this agent:
    runAsUser: 0
    volumes:
    - type: persistentVolumeClaim
      claimName: "fspin-mirror-pvc"
      mountPath: "/mirror"
      readOnly: false

serviceAccountAgent:
  name: fspin-jenkins-agent
  create: false
