master:
  serviceType: ClusterIP
  ingress:
    enabled: true
    hostName: "jenkins.fspin.org"
    annotations:
      kubernetes.io/ingress.class: traefik
  tag: "lts"
  installPlugins:
    - kubernetes:1.26.4
    - workflow-aggregator
    - workflow-job
    - credentials-binding
    - git
    - openid
    - matrix-auth

agent:
  image: gcr.io/fspin-265404/fspin-jenkins-runner
  tag: "latest"
  podName: fspin-jenkins-run
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"

serviceAccountAgent:
  name: fspin-jenkins-agent
  create: false
