Master:
  ServiceType: ClusterIP
  HostName: "jenkins.fspin.org"
  Ingress:
    Annotations:
      kubernetes.io/ingress.class: traefik
  InstallPlugins:
    - kubernetes:1.12.6
    - workflow-aggregator:2.5
    - workflow-job:2.25
    - credentials-binding:1.16
    - git:3.9.1
    - openid:2.2
    - matrix-auth:2.3

Agent:
  Image: gcr.io/fspin-199819/fspin-jenkins-runner
  ImageTag: "latest"
  resources:
    requests:
      cpu: "200m"
      memory: "1024Mi"
    limits:
      cpu: "1"
      memory: "1024Mi"

rbac:
  install: true
  serviceAccountName: fspin-jenkins
  apiVersion: v1beta1
  roleRef: cluster-admin
