Master:
  ServiceType: ClusterIP
  HostName: "jenkins.fspin.org"
  Ingress:
    Annotations:
      kubernetes.io/ingress.class: traefik
  InstallPlugins:
    - kubernetes:1.10.1
    - workflow-aggregator:2.5
    - workflow-job:2.23
    - credentials-binding:1.16
    - git:3.9.1
    - openid:2.2

Agent:
  Image: gcr.io/fspin-199819/fspin-jenkins-runner
  ImageTag: "latest"

rbac:
  install: true
  serviceAccountName: fspin-jenkins
  apiVersion: v1beta1
  roleRef: cluster-admin
