#!/bin/bash
# Build updated GCE images with packer
# Clean up old images
set -x
export SNAPSHOT_ID=$(wget -q -O - https://repo.fspin.org/latest_snapshot)
[[ -z "${SNAPSHOT_ID}" ]] && exit 1
BUILDER_IMAGES=5
FEDORA_VERSION=37
envsubst '${SNAPSHOT_ID}' < "fspin.repo" > "fspin-snapshot.repo" && \
envsubst '${SNAPSHOT_ID}' < "fspin-repo.ks" > "fspin-snapshot-repo.ks" && \
envsubst '${SNAPSHOT_ID}' < "fspin-x86-64-builder.json" > "fspin-snapshot-${FEDORA_VERSION}-x86-64-builder.json" && \
envsubst '${SNAPSHOT_ID}' < "mock-fspin-x86_64.cfg" > "mock-snapshot-fspin-f${FEDORA_VERSION}-x86_64.cfg" && \
\rm fspin.repo fspin-repo.ks "fspin-x86-64-builder.json" "mock-fspin-x86_64.cfg" && \
echo "export SNAPSHOT_ID=${SNAPSHOT_ID}" > snapshot_id && \
echo "export SPIN_ID=`echo ${SNAPSHOT_ID}|awk -F- '{print $1$2$3}'`" >> snapshot_id && \
echo "Creating builder for F${FEDORA_VERSION}..." && \
/bin/packer build -force /opt/fspin-snapshot-${FEDORA_VERSION}-x86-64-builder.json && \
echo "Cleaning out stale images..."
result=$?
images=(); while read i; do images+=("$i"); done < <(gcloud compute images list --filter="name~fspin-[0-9]+-x86-64" --sort-by="~creationTimestamp" --format="json(NAME)"|jq -r .[].name) && \
for image in ${images[@]:${BUILDER_IMAGES}}; do gcloud compute images delete $image; done
exit $result
