#!/bin/bash
# Generate source ISO for all F27 x86_64 spins
set -x
source /tmp/snapshot_id
pushd /usr/share/spin-kickstarts
\cp -f /tmp/fspin-snapshot-repo-not-rawhide-with-source.ks fedora-repo-not-rawhide.ks
sed -i '/%include fedora-repo.ks/d' fedora-live-base.ks
cp /tmp/all-spins.ks .
ksflatten --config all-spins.ks -o flat-all.ks --version F27
pungi -G -c flat-all.ks --name ${SPIN_ID} --ver 27 --force
pungi -C -c flat-all.ks --name ${SPIN_ID} --ver 27 --force
pungi -I -c flat-all.ks --name ${SPIN_ID} --ver 27 --sourceisos --force
popd
pushd /usr/share/spin-kickstarts/27/source/iso
sha512sum *.iso > CHECKSUM512-${SPIN_ID}-DVD-source-27
transmission-create -p -s 2048 \
        -c "ISO SHA512SUM: $(cat CHECKSUM512*)" \
        -t http://respins.fedorainfracloud.org:6969/announce \
        -o ${SPIN_ID}-DVD-source-27.torrent \
        ${SPIN_ID}-DVD-source-27.iso
popd
