#!/bin/bash
# Compose from upstream Fedora 27 x86_64 mate-compiz
source /tmp/snapshot_id
export SPIN_ID=`echo $SNAPSHOT_ID|awk -F- '{print $1$2$3}'`
export SPIN_SHORT_NAME=`echo mate-compiz|cut -c1-4|awk '{print toupper($0)}'`
pushd /usr/share/spin-kickstarts
cp /tmp/fspin-snapshot-repo-not-rawhide-with-source.ks fedora-repo-not-rawhide.ks
mv fedora-live-mate_compiz.ks fedora-live-mate-compiz.ks
ksflatten --config fedora-live-mate-compiz.ks -o flat-fedora-live-mate-compiz.ks --version F27
livemedia-creator --ks flat-fedora-live-mate-compiz.ks --no-virt --resultdir /var/lmc --project F27-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live --make-iso --volid F27-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live --iso-only --iso-name F27-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live.iso --releasever 27 --title F27-${SPIN_SHORT_NAME}-x86_64-${SPIN_ID}-Live --macboot
popd
